<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>unistackbot_bringup</name>
  <version>0.1.0</version>
  <description>顶层启动包，负责拉起 UniStackBot 各功能节点并加载运行参数。</description>
  <maintainer email="todo@todo.todo">UniStackBot</maintainer>
  <license>TODO: Declaration of license</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>forward_command_controller</exec_depend>
  <exec_depend>unistackbot_controller</exec_depend>
  <exec_depend>unistackbot_description</exec_depend>
  <exec_depend>unistackbot_hardware</exec_depend>
  <exec_depend>unistackbot_hardware_mock</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
