<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>unistackbot_controller</name>
  <version>0.1.0</version>
  <description>运动控制层：形态盲运动学库（URDF FK+雅可比）+ 算法控制器插件模板（骨架）。</description>
  <maintainer email="todo@todo.todo">UniStackBot</maintainer>
  <license>TODO: Declaration of license</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>orocos_kdl_vendor</depend>
  <depend>orocos_kdl</depend>
  <depend>urdf</depend>
  <depend>urdfdom</depend>
  <depend>kdl_parser</depend>
  <depend>eigen</depend>
  <depend>unistackbot_interface</depend>
  <depend>interactive_markers</depend>
  <depend>visualization_msgs</depend>
  <depend>rclcpp_action</depend>
  <depend>control_msgs</depend>
  <depend>trajectory_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
