<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>unistackbot_hardware_mock</name>
  <version>0.1.0</version>
  <description>仿真通信硬件层,提供与仿真器通信的 hardware_interface 插件,接口与 unistackbot_hardware 对齐。</description>
  <maintainer email="todo@todo.todo">UniStackBot</maintainer>
  <license>TODO: Declaration of license</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <pluginlib plugin="hardware_plugin.xml" />
  </export>
</package>
